install: copy
	python ~/.vim/bundle/YouCompleteMe/install.py --gocode-completer --clang-completer
	cp ~/.vim/bundle/YouCompleteMe/third_party/ycmd/examples/.ycm_extra_conf.py ~/

copy:
	cp vimrc ~/.vimrc

